backend:
  build: ./backend
  container_name: lancon-backend
  ports:
    - "8000:8000"
  env_file:
    - .env
  environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
  volumes:
    - ./backend:/app
  depends_on:
    - frontend
