version: "3.9"

services:
  backend:
    build: ./backend
    container_name: lancon-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    volumes:
      - ./backend:/app
      - ./backend/app/service-account-key.json:/app/service-account-key.json:ro

  frontend:
  build:
    context: ./frontend
    args:
      - REACT_APP_API_URL=/api
  environment:
    - REACT_APP_API_URL=/api
  container_name: lancon-frontend
  ports:
      - "3000:80"
  environment:
      - REACT_APP_API_URL=http://backend:8000
  stdin_open: true
  tty: true
