version: '3.9'

services:
  backend:
    build: ./backend
    container_name: lancon-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: lancon-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
