services:
  backend:
    build: ./backend
    container_name: lancon-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    volumes:
      - ./backend:/app
      - ./backend/app/service-account-key.json:/app/service-account-key.json:ro
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: lancon-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
